server:
  port: 9527

eureka:
  client:
    # fetch period time
    registry-fetch-interval-seconds: 5
    # register center addr
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-zuul_9527
    prefer-ip-address: true
    #ip-address: 127.0.0.1

zuul:
  routes:
    # here service name define by yourself
    dept-service:
      # define route path mapping.
      path: /dept/**
      serviceId: microservicecloud-dept